### ISSUE TITLE
Enhancement: Add default timeout for Ansible get_url options

### ISSUE THREAD

**Issue by malvidin** [splunk/attack_range_local#38]
The default timeout may not work for all URLs retrieved. Adding a default "url_timeout" would allow setting a default in one location, rather than finding all locations where a get_url may timeout. 

The Splunk and ESCU downloads have both taken longer than the default timeout (10s), causing build failures.  

```
- name: download splunk
  tags: install
  get_url:
    url: '{{ splunk_url }}'
    dest: /opt/
    timeout:  30
  when: splunk_path.stat.exists == false
```

or to scale based on the size of the download or hosting provider:
```
- name: download splunk
  tags: install
  get_url:
    url: '{{ splunk_url }}'
    dest: /opt/
    timeout:  '{{  url_timeout * 4 }}'
  when: splunk_path.stat.exists == false
```
